; Benign structural lookalike: a legitimately licensed NetSupport Manager
; client32.ini as deployed by an IT department. Shares the product's
; driver name (nskbfltr), gateway/silent-mode keys and HTTP-port shape,
; but none of the campaign's license / operator path / gateway hosts.
; Must NOT match.
[Client]
Quiet=0
SilentDisconnect=0
ShowIcon=1
DisableChat=0
DisableMessage=0
[HTTP]
GatewayAddress=nsm-gateway.corp.example.com
GSK=XXXXXXXXXXXXXXXXXXXXXXXX
Port=443
SecondaryGateway=nsm-gateway2.corp.example.com
[_License]
licensee=Example Corp IT
serial_no=NSM300034
maxslots=500
expiry=31/12/2027
[General]
ControlKey=
KeyboardFilter=nskbfltr
InstallPath=C:\Program Files (x86)\NetSupport\NetSupport Manager\
[Audio]
DisableAudio=0
